#define CHAN_FRONT_LEFT_DRIVE_TALON					0
#define CHAN_FRONT_RIGHT_DRIVE_TALON				1
#define CHAN_REAR_LEFT_DRIVE_TALON					2
#define CHAN_REAR_RIGHT_DRIVE_TALON					3
#define CHAN_CLAMP_TALON										4

#define OPENED_WIDE														1
#define OPENED_NARROW												2

#define POSITION_ONE													1
#define POSITION_TWO 													2
#define POSITION_THREE													3
#define POSITION_FOUR												4

#define CLOSED_POSITION												1

//Driver Station Box Buttons
#define BOX_CLOSE_BUTTON
#define BOX_OPEN_NARROW_BUTTON
#define BOX_OPEN_WIDE_BUTTON
#define BOX_RELEASE_NARROW_BUTTON
#define BOX_RELEASE_WIDE_BUTTON

#define BOX_MOVE_POSITION_ONE_BUTTON
#define BOX_MOVE_POSITION_TWO_BUTTON
#define BOX_MOVE_POSITION_THREE_BUTTON
#define BOX_MOVE_POSITION_FOUR_BUTTON
//Driver Station Box LEDs
#define BOX_CLOSE_STATE_LED
#define BOX_OPEN_NARROW_STATE_LED
#define BOX_OPEN_WIDE_STATE_LED
#define BOX_RELEASE_NARROW_STATE_LED
#define BOX_RELEASE_WIDE_STATE_LED

#define BOX_MOVE_POSITION_ONE_STATE_LED
#define BOX_MOVE_POSITION_TWO_STATE_LED
#define BOX_MOVE_POSITION_THREE_STATE_LED
#define BOX_MOVE_POSITION_FOUR_STATE_LED

